Neovici/cosmoz-input

- cosmoz-input.js
> fix: improve maintain focus

- cosmoz-input.js
Improve cosmoz-input style compatibility
Restores some compatibility with paper-input styles.
> fix: improve cosmoz-input style compatibility

- cosmoz-input.js
> fix: improve style compat

- cosmoz-input.js
> fix: adjust default error color

- cosmoz-input.js
> fix: correct padding css variable

- cosmoz-input.js
use position absolute for error
> fix: use position absolute for error

- cosmoz-input.js
Adds pattern attribute and validate function to cosmoz-input
> feat: add pattern and validate

- cosmoz-input.js
- test/cosmoz-input.test.js
Adds `allowed-pattern` which specifies a regexp to match
newly inputed chars against
> feat: adds allowed-pattern support

- use-input.js
don't prevent default on mousedown on textarea
> fix: don't prevent default on mousedown on textarea

- package-lock.json
- styles.js
When input is empty allow clicking the number spin/stepper button.
> fix(input): correct z-index for number spin button

- .github/workflows/ci.yml
- package-lock.json
- package.json
- styles.js
Set position relative on host otherwise the error message
can be weirdly displayed.
> fix(style): position relative

- package-lock.json
- package.json
- styles.js
Better organize css variables, usage & fallback.
> feat(styles): reorganize css variables

- cosmoz-input.js
- cosmoz-textarea.js
- render.js
Add `maxlength` attribute support.
> feat: add `maxlength` attribute support

- src/use-input.ts
fix for isolated mousebtn and blur events
> feat: fix for isolated mousebtn and blur events

- .eslintignore
- .gitignore
- src/cosmoz-input.ts
- src/cosmoz-textarea.ts
- src/render.ts
- src/styles.ts
- src/use-allowed-pattern.ts
- src/use-auto-height.ts
- src/use-input.ts
- stories/cosmoz-input.stories.js
- test/cosmoz-input.test.js
Add autosize/ autoexpand functionality to inputs.
> feat: auto expand

- src/styles.ts
> fix(input): autosize with min-content

- src/styles.ts
> fix(input): autosize control max width

- src/styles.ts
Set the input background on the wrap element so that it covert suffix
and prefix too.
> feat(input): bg on wrap

- src/cosmoz-textarea.ts
- src/styles.ts
Inherit font-family from host.
> feat(style): inherit font family

- src/styles.ts
- stories/cosmoz-input.stories.js
New feature related to [AB#10075](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/10075) - added a Storybook for the testing of the color input.
> Added a storybook for color input

- src/cosmoz-input.ts
- src/cosmoz-textarea.ts
- src/use-input.ts
Use a ref to access the input element.
> feat(cosmoz-input): get input with useRef

- src/use-input.ts
> feat: remove onInputRef

- src/styles.ts
> feat(input): add line color variable

- src/styles.ts
Feature [AB#10575](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/10575) and [AB#11519](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/11519) - Step 1: creation of a new comment textarea and of a search input.
https://github.com/Neovici/cosmoz-input/assets/122988480/179a3c15-354a-40f1-b151-64f114f5da48
> New CSS vars for styling of cosmoz-input

- stories/cosmoz-input.stories.js
Polishing of a [previous PR](https://github.com/Neovici/cosmoz-input/pull/63/) - addition of a story showing the usage of the new styling variables on a scoped input tag.
> fix: added a story containing scoped styling

- src/styles.ts
Re https://neovici.slack.com/archives/C6LJQMJFM/p1696368508877459
> fix(disabled): user cannot select text in a disabled input

- .github/workflows/storybook.yml
- package-lock.json
- package.json
Update dependencies and workflows.
> feat: update dependencies and workflows

- package-lock.json
- src/cosmoz-input.ts
Observe the `label` attribute.
> Observe  the `label` attribute

- src/styles.ts
- stories/cosmoz-input.stories.js
Feature [AB#11519](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/11519) - new vars for styling cosmoz-inputs in a scoped way.
https://github.com/Neovici/cosmoz-input/assets/122988480/7b974f5f-20e4-4b52-b3d5-1d91351a7394
> feat(input): new vars for updating styling

- package-lock.json
- package.json
- src/cosmoz-input.ts
- src/cosmoz-textarea.ts
- src/use-allowed-pattern.ts
- src/use-auto-height.ts
- src/use-input.ts
BREAKING CHANGE: Update to @pionjs/pion and allow lit-html@3
> feat: update to pion

- src/styles.ts
- stories/cosmoz-input.stories.js
Further tweaks for styling vars in the input component.
Add variables to enable contour styling of input element.
Also change the caret color to match the current state.
> feat(input): add contour styling

- src/styles.ts
- stories/cosmoz-input.stories.js
- stories/cosmoz-textarea.stories.js
Feature [AB#11519](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/11519) - styling tweaks on `cosmoz-textarea` to align it to the contour styling.
https://github.com/Neovici/cosmoz-input/assets/122988480/23a1af7c-b8bf-4be4-a282-9abf7093f5d6
> feat(cosmoz-textarea): new contour styling for textarea

- src/styles.ts
- stories/cosmoz-input.stories.js
- stories/cosmoz-textarea.stories.js
- stories/style.js
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1711093197592089
> fix: inherit font-family by default

- src/use-input.ts
Make `<input>` focused when clicking on `<cosmoz-input>`
> fix: make input focus on cosmoz-input click

- src/use-input.ts
This reverts commit 6487f856cf731b18a0094506038b5f558dca8ecb.
Re https://neovici.slack.com/archives/C6LJQMJFM/p1726562478223159
> fix: inputs are unselectable

- src/cosmoz-input.ts
- src/cosmoz-textarea.ts
- stories/cosmoz-input.stories.js
- test/cosmoz-input.test.js
- test/cosmoz-textarea.test.js
Fix [Cannot set placeholder via attribute](https://github.com/Neovici/cosmoz-input/issues/105)
> fix: add placeholder attribute
